/* Generated By:JavaCC: Do not edit this line. MediaWikiParserConstants.java */
package haui.office.wiki.parser;

public interface MediaWikiParserConstants {

  int EOF = 0;
  int ANY = 1;
  int EMPTY = 2;
  int SPACE_CHAR = 3;
  int SPACE = 4;
  int IDENTIFIER_START_CHAR = 5;
  int IDENTIFIER_CHAR = 6;
  int IDENTIFIER = 7;
  int QUOTED_STRING = 8;
  int APOSTROPHED_STRING = 9;
  int STRING_CONSTANT = 10;
  int SINGLE_SPECIAL = 11;
  int URL_SUFFIX = 12;
  int NEWLINE = 13;
  int TABLE_BEGIN = 14;
  int TABLE_ROW = 15;
  int TABLE_HEAD_I = 16;
  int TABLE_CELL_I = 17;
  int TABLE_CAPTION = 18;
  int TABLE_END = 19;
  int HEADING_START = 20;
  int PRE = 21;
  int ATTRIBUTE_NAME = 22;
  int ASSIGN = 23;
  int ATTRIBUTE_VALUE = 24;
  int ATTRIBUTE_SEPARATOR = 25;
  int END_OF_ATTRIBUTES = 26;
  int BULLET = 27;
  int HASH = 28;
  int INDENT = 29;
  int LIST_PREFIX_END = 30;
  int PARAGRAPH_TEXT = 31;
  int LINE_TEXT = 32;
  int OPEN_WIKI_LINK_RAW = 33;
  int OPEN_WIKI_LINK = 34;
  int OPEN_EXTERNAL_LINK = 35;
  int CLOSE_WIKI_LINK = 36;
  int CLOSE_EXTERNAL_LINK = 37;
  int OPEN_PENTUPLE_CURLY = 38;
  int OPEN_TEMPLATE4 = 39;
  int OPEN_TEMPLATE_VAR = 40;
  int OPEN_TEMPLATE2 = 41;
  int CLOSE_PENTUPLE_CURLY = 42;
  int CLOSE_TEMPLATE4 = 43;
  int CLOSE_TEMPLATE_VAR = 44;
  int CLOSE_TEMPLATE2 = 45;
  int BOLD_ITALICS = 46;
  int BOLD = 47;
  int ITALICS = 48;
  int BEGIN_EXTENSION = 49;
  int END_EXTENSION = 50;
  int BEGIN_COMMENT = 51;
  int URL = 52;
  int HEADING_END = 53;
  int TABLE_CELL = 54;
  int TABLE_HEAD = 55;
  int PIPE = 56;
  int COMMENT_TEXT = 57;
  int END_COMMENT = 58;
  int EXTENSION_NAME = 59;
  int EXTENSION_ASSIGN = 60;
  int EXTENSION_VALUE = 61;
  int EXTENSION_SPACE = 62;
  int EXTENSION_CLOSE = 63;
  int EXTENSION_CANCEL = 64;
  int APOSTROHE_TEXT = 65;
  int APOSTROHE_END = 66;
  int END_OF_LINE_CONTENTS = 67;
  int BLANK_LINE = 68;

  int APOSTROHE_CATASTROPHE = 0;
  int EXTENSION = 1;
  int COMMENT = 2;
  int LINE_CONTENTS = 3;
  int LIST_PREFIX = 4;
  int ATTRIBUTE_CONTENTS = 5;
  int DEFAULT = 6;

  String[] tokenImage = {
    "<EOF>",
    "<ANY>",
    "<EMPTY>",
    "<SPACE_CHAR>",
    "<SPACE>",
    "<IDENTIFIER_START_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<QUOTED_STRING>",
    "<APOSTROPHED_STRING>",
    "<STRING_CONSTANT>",
    "<SINGLE_SPECIAL>",
    "<URL_SUFFIX>",
    "<NEWLINE>",
    "<TABLE_BEGIN>",
    "<TABLE_ROW>",
    "<TABLE_HEAD_I>",
    "<TABLE_CELL_I>",
    "<TABLE_CAPTION>",
    "<TABLE_END>",
    "<HEADING_START>",
    "\" \"",
    "<ATTRIBUTE_NAME>",
    "\"=\"",
    "<ATTRIBUTE_VALUE>",
    "<ATTRIBUTE_SEPARATOR>",
    "<END_OF_ATTRIBUTES>",
    "\"*\"",
    "\"#\"",
    "\":\"",
    "<LIST_PREFIX_END>",
    "<PARAGRAPH_TEXT>",
    "<LINE_TEXT>",
    "\"[[:\"",
    "\"[[\"",
    "\"[\"",
    "\"]]\"",
    "\"]\"",
    "\"{{{{{\"",
    "\"{{{{\"",
    "\"{{{\"",
    "\"{{\"",
    "\"}}}}}\"",
    "\"}}}}\"",
    "\"}}}\"",
    "\"}}\"",
    "\"\\\'\\\'\\\'\\\'\\\'\"",
    "\"\\\'\\\'\\\'\"",
    "\"\\\'\\\'\"",
    "\"<\"",
    "\"</\"",
    "\"<!--\"",
    "<URL>",
    "<HEADING_END>",
    "<TABLE_CELL>",
    "<TABLE_HEAD>",
    "\"|\"",
    "<COMMENT_TEXT>",
    "\"-->\"",
    "<EXTENSION_NAME>",
    "\"=\"",
    "<EXTENSION_VALUE>",
    "<EXTENSION_SPACE>",
    "\">\"",
    "<EXTENSION_CANCEL>",
    "<APOSTROHE_TEXT>",
    "<APOSTROHE_END>",
    "<END_OF_LINE_CONTENTS>",
    "<BLANK_LINE>",
  };

}
